Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", path: "init-server.sh"
  config.vm.network "forwarded_port", host: 8080, guest: 8080
  config.vm.network "forwarded_port", host:30022, guest:30022
  config.vm.synced_folder "data", "/data/"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
