apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
      zone: prod
      version: v1
  
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data
