Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname="master"
    master.vm.provision "shell", path: "init-server.sh"
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "centos/7"
    node01.vm.hostname="node01"
    node01.vm.provision "shell", path: "init-server.sh"
  end

  config.vm.define "node02" do |node02|
    node02.vm.box = "centos/7"
    node02.vm.hostname="node02"
    node02.vm.provision "shell", path: "init-server.sh"
  end

end
